= Mod-it [![Build Status](https://travis-ci.org/mypsycho/ModIt.svg?branch=master)](https://travis-ci.org/mypsycho/ModIt)

Mod-it library provides an API to ease creations of EMF Models in XTend.

EMod-it extension frees developers of tedious EMF factory syntax making model description close to JSon file.
It also suppresses the sequential constraint of code by providing a registry and resolving references in assemble phase.

Using such syntax helps to:
 * Speed up the creation of tests
 * Improve the readability of the tests
 * Improve maintainability when the tested metamodel changes
 * Ease the creation of inter-connected models

It has been created and used in industrial projects to ease the creation input for JUnit tests on the metamodel and business rules.

== Content (work in progress...)

It also comes with various functions:
 * EMF enrichment where user can associate properties and lambda to metamodel and providing pseudo multi-inheritance for EObject. 
 * EReversIt generates Xtend source from existing models providing round-trips for tests routine. 
 * EMF Sirius integration to write Sirius model in textual mode and lambda in xtend (instead of AQL).
 * i18n classes to use xtend template instead of properties syntax.

See documentation and binaries at ...


== Contributing

1. Fork it!

2. Create your feature branch: `git checkout -b my-new-feature`

3. Commit your changes: `git commit -am 'Add some feature'`

4. Push to the branch: `git push origin my-new-feature`

5. Submit a pull request.

== License
[Eclipse Public License - v 1.0](https://www.eclipse.org/legal/epl-v10.html)  
[Contribution guidelines for this project](docs/CONTRIBUTING.md)
