= Feedback: Building a DSL with Eclipse Sirius 
:source-highlighter: highlightjs
:revealjs_center: false
:customcss: compact.css

== Overview

=== Context

Project to convert Rational Rose Extensions into Eclipse plugins

* By translating UML stereotypes into Ecore classes

Targeted DSL was important : 300+ classes, 350+ properties

* A lot of Stereotype packages transformed into 4 Emf Packages

Edition features

* Few types of diagrams were expected (4)  
* but all properties to edit through Sirius:EEF and dispatched in 4 tabs.

=== Presented points

* Structural organization (in-short)
* Eclipse plugins development

== Structural organization: In-short

=== Chosen factory

Code: Maven/tycho, gerrit, Jenkins, Oomph, 

Doc/management: Jira/confluence (Model-Driven agile!)

=== Notable elements

A replicable structure for POM as the project are divided in 3 Gits

Layout files to keep consistency between oomph descriptors and Maven/Typho TPD

Reproducing Eclipse Nature philosophy in POMs using POM Parent and profile
* For example: Xtend or projecting including code generation

== Development : Limits of model-driven approach

=== Genmodel

A lot a boiler plates in code and hard to identify specific from mundane.

Poor handling of multi-inheritance.

Customization of ItemProviderAdapter is painful.

* Even with EmfLoopHole, each sub-class needed to be rewritten.

Editing plugin.properties file was difficult with this number of EMF elements.

* Renaming/refactoring adds pollution

=== Writting Sirius Model

(Un)Fortunately so repetitive 

(Compelled)Possibility to dev of a creation wizard.

As one-shoot strategy, wizard lacks flexibility when modifying Meta-Model.

**Resulting ODesign is huge !**

== Retrospective analysis

=== Needs ?

Extend meta-model in seamless way with the implementation

Avoid generation for customization an Ecore Element

Modifications of meta-model leads to compilation error

=== Constraints

Different aspects should be attached in a readable unit of code. 

No massive switch forcing functional rules to be separated

In fact, developer should be able to choose between  

** grouping by feature (validation, edition, ...)
** grouping by semantic (package or EClass) 

Example: display, validation and specific actions of 1 element should be in 1 class.

== Proposition

Extending meta-model by code

* Readable syntax (no eAnnotation)
* Real typed-approach (no symbolic code like in plugin.xml extensions)

[%notitle]
=== Code sample
[source]
----
XxNamedElement += #[ // A Emf Class is extended
  String->[XxNamedElement| name ], // ItemProvider label provider
  Diagnostic->#[ // Validation Defining validation rule
    "EmptyName"->error->[XxNamedElement| name==null || name.trim.empty ],
    "HiddenCar"->warning->[XxNamedElement| name!=null && name.trim != name ],
  ]
]
// Extended features
//-- EEF: Property accepts carriage return.
abstractConstrainedMethod_Precondition += multiline
abstractConstrainedMethod_Postcondition += multiline
abstractError_QualifiedName += shown
abstractError_Domain += shown
abstractExtendedReturningMethod_ReturnTypeDocumentation += #[ Tab->Tab.documentation, multiline ]
abstractReturningMethod_ReturnTypeDocumentation += #[ Tab->Tab.documentation, multiline ]
//-- EEF: Property in a specific category.
abstractRootElement_StandardGeneration += Tab->Tab.generation
abstractRootElement_ErrorGeneration += Tab->Tab.generation
abstractType_AllAttributes += hidden
basicType_MomTypeClass += Tab->Tab.generation
----

== How to use
Project https://github.com/mypsycho/modit

=== Available API 

A singleton of EmfStrecher works on a group of EPackage, registers specificities and provides inheritance mechanism.

EmfContribution provides a factory to initialize extensions of EPackage into the singleton.

Major functions (edit, validated, etc) supported by 1 engine based on EmfContribution keys and running with an EmfStrecher.

=== Example for Sirius

Definition of singleton : EqxModelExtensions

Contribution of model : EquinoxeCoreContrib, EquinoxeComposantsMetierContrib, …

link:https://github.com/mypsycho/ModIt/tree/master/tests/reversit-tests/src-gen/fr/ibp/odv/xad2/rcp/model[code sample]

Engine of Sirius (limited to EEF part) : 1 simple class (<500 lines)

link:https://github.com/mypsycho/ModIt/blob/master/tests/reversit-tests/src/org/mypsycho/emf/modit/reverit/test/SiriusGenerator.xtend[SiriusGenerator]

== Complements

=== Reverse engineer of existing models (genmodel, sirius, test)

EReversIt can generate Xtend classes matching any EMF model.

Eases detection of pattern in models.

Use case: Round-trip with Sirius
* Edit in run mode
* Reverse to code
* Update engine accordingly

=== I18n alternative using Xtend syntax

Syntax of i18n Edit plugin or Eclipse is messy and limited

Xtend syntax leads to a Class-based implementation 

Typed approach (not only String)

Using Xtend template instead of tricky pseudo MessageFormat

== Possible complements

=== ItemProviderAdapterFactory <In progress>

Behavior can be customize endlessly (genmodel is limited by its model)

Each function have a default behavior which can be overridden

=== Other fields of interest

Validation, actions

=== Existing POC

EEF Group for Sirius

