<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DummyWorld" nsURI="https://github.com/mypsycho/modit/tests/dummy-world/1.0"
    nsPrefix="dw">
  <eClassifiers xsi:type="ecore:EClass" name="Contact" abstract="true" eSuperTypes="#//Named">
    <eStructuralFeatures xsi:type="ecore:EReference" name="locations" upperBound="-1"
        eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uses" upperBound="-1" eType="#//Service"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owns" unique="false" upperBound="-1"
        eType="#//Good"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" eSuperTypes="#//Contact #//Indexed">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Company" eSuperTypes="#//Titled #//Contact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees" upperBound="-1"
        eType="#//Job"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="offers" upperBound="-1"
        eType="#//Offer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Directory">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contacts" upperBound="-1"
        eType="#//Contact" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1"
        eType="#//Activity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Named" abstract="true" interface="true">
    <eOperations name="getName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="#//Titled"/>
  <eClassifiers xsi:type="ecore:EClass" name="Titled" eSuperTypes="#//Named">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location" eSuperTypes="#//Titled">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Offer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prices" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Job" eSuperTypes="#//Titled">
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" lowerBound="1"
        eType="#//Person"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//Titled #//Offer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Service" eSuperTypes="#//Offer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
        eType="#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Good" eSuperTypes="#//Indexed">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Product"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bought" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Indexed">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hint" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EStringToStringMapEntry"/>
  </eClassifiers>
</ecore:EPackage>
