/** 
 */
package org.mypsycho.emf.modit.dw.dummyworld.provider

import org.mypsycho.emf.modit.dw.dummyworld.DwPackage
import org.mypsycho.emf.modit.dw.dummyworld.Job
import org.mypsycho.emf.modit.dw.dummyworld.Person
import org.mypsycho.emf.modit.dw.dummyworld.Titled
import org.mypsycho.emf.modit.edit.ModitItemProviderAdapterFactory

import static org.mypsycho.emf.modit.edit.ModitEditLabels.*
import static org.mypsycho.emf.modit.edit.ModitEditListeners.*


/** 
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * <p>
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * </p>
 */
class DwIpAdapterFactory extends ModitItemProviderAdapterFactory {
	
	static val PKG = DwPackage.eINSTANCE
	

	/** 
	 * This constructs an instance.
	 * 
	 * @generated
	 */
	new() {
		super(DwEditPlugin.INSTANCE)
		
		// this should be static but if static on to get a locale ??
		Titled<<TEXT += [ name ]
		Person<<TEXT += [ firstname + ' ' + lastname ]
		Job<<TEXT += [ //
			if (employee !== null) '''«employee*TEXT» («name»)'''
			else '''unaffected «name»'''
		]
		Job<<(DEPENDENCIES) += #[ PKG.job_Employee ]
		
	}
}
