/**
 */
package org.mypsycho.emf.modit.dw.dummyworld.provider;

import org.mypsycho.emf.modit.dw.dummyworld.DwPackage;
import org.mypsycho.emf.modit.edit.ModitItemProviderAdapterFactory;
import org.mypsycho.modit.emf.stretch.EmfStretcher;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class DwModitIPAdapterFactory extends ModitItemProviderAdapterFactory {
	
	
	public static final EmfStretcher STRETCHER = new EmfStretcher(DwPackage.eINSTANCE);

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DwModitIPAdapterFactory() {
		super(DummyWorldEditPlugin.INSTANCE, STRETCHER);
	}


}
